Description of test_3d_resistor
Home > eidors > tests > test_3d_resistor.m
test_3d_resistor
PURPOSE
Create 3D model of a Rectangular resistor
SYNOPSIS
function test_3d_resistor(opt)
DESCRIPTION
 Create 3D model of a Rectangular resistor
 $Id: test_3d_resistor.m 7100 2024-12-26 12:05:50Z aadler $
CROSS-REFERENCE INFORMATION
This function calls:
np_calc_jacobian NP_CALC_JACOBIAN: J= np_calc_jacobian(fwd_model, img)
np_fwd_solve NP_FWD_SOLVE: data= np_fwd_solve(fwd_model, img)
eidors_obj EIDORS_OBJ: maintains EIDORS internals
show_fem SHOW_FEM: show the EIDORS3D finite element model
mdl_normalize MDL_NORMALIZE Check or set the normalize_measurements flag on a model.
mk_grid_model MK_GRID_MODEL: Create reconstruction model on pixelated grid
mk_image MK_IMAGE: create eidors image object
stim_meas_list STIM_MEAS_LIST: mk stimulation pattern from list of electrodes
calc_jacobian CALC_JACOBIAN: calculate jacobian from an inv_model
find_boundary [srf, idx] = find_boundary(simp);
fwd_solve_1st_order FWD_SOLVE_1ST_ORDER: data= fwd_solve_1st_order(img)
jacobian_adjoint JACOBIAN_ADJOINT: J= jacobian_adjoint(img)
jacobian_perturb JACOBIAN_PERTURB: J= jacobian_perturb(fwd_model, img)
system_mat_1st_order SYSTEM_MAT_1ST_ORDER: SS= system_mat_1st_order(fwd_model, img)
fwd_solve FWD_SOLVE: calculate data from a fwd_model object and an image
unit_test_cmp UNIT_TEST_CMP: compare matrices in eidors output
This function is called by:
np_fwd_solve NP_FWD_SOLVE: data= np_fwd_solve(fwd_model, img)
fwd_solve_1st_order FWD_SOLVE_1ST_ORDER: data= fwd_solve_1st_order(img)
jacobian_adjoint JACOBIAN_ADJOINT: J= jacobian_adjoint(img)
system_mat_1st_order SYSTEM_MAT_1ST_ORDER: SS= system_mat_1st_order(fwd_model, img)
SUBFUNCTIONS
function vals = resistor_test;
function cleaner_code
SOURCE CODE
% Create 3D model of a Rectangular resistor
% $Id: test_3d_resistor.m 7100 2024-12-26 12:05:50Z aadler $
function test_3d_resistor(opt)
if nargin>0 && strcmp(opt,'UNIT_TEST'); resistor_test; return; end
resistor_test;
function vals = resistor_test;
ll=5*1; % length
ww=1*2; % width
hh=1*3; % height
conduc= .13;  % conductivity in Ohm-meters
current= 4;  % Amps
z_contact= 1e-1;
scale = .46;
mdl= eidors_obj('fwd_model','3D rectangle');
nn=0;
for z=0:ll; for x=0:ww; for y=0:hh
   nn=nn+1;
   mdl.nodes(nn,:) = [x,y,z];
end; end; end
if 0
% Matlab's delaunayn triangularization is screwed up
   mdl.elems = delaunayn(mdl.nodes);
elseif 0
% Matlab's delaunay3 triangularization is screwed up
   mdl.elems = delaunay3(mdl.nodes(:,1), mdl.nodes(:,2), mdl.nodes(:,3));
elseif 0
   elem1= [ 1 2 3 5; 5 6 2 3; 5 6 7 3; ...
            4 2 3 8; 8 6 2 3; 8 6 7 3;];
   mdl.elems=[];
   for i=0:ll-1;
       mdl.elems= [mdl.elems; elem1+4*i];
   end
else
   mdl= mk_grid_model([],0:ww,0:hh,0:ll);
   mdl.nodes= mdl.nodes*scale;
   mdl= rmfield(mdl,'coarse2fine');
end
mdl.boundary= find_boundary(mdl.elems);
mdl.gnd_node = 1;
elec_nodes= [1:(ww+1)*(hh+1)];
elec(1).nodes= elec_nodes;      elec(1).z_contact= z_contact;
elec(2).nodes= nn-elec_nodes+1; elec(2).z_contact= z_contact;
stim.stim_pattern= [-1;1]*current;
stim.meas_pattern= [-1,1];
mdl.stimulation= stim;
mdl.electrode= elec;
show_fem(mdl);
mdl = mdl_normalize(mdl,0);
mdl.solve = @fwd_solve_1st_order;
mdl.system_mat = @system_mat_1st_order;
n_el = size(mdl.elems,1);
img= eidors_obj('image','3D rectangle', ...
      'elem_data', ones(n_el,1) * conduc, ...
      'fwd_model', mdl);
fsol= fwd_solve(img);
fprintf('Solver %s: %f\n', fsol.name, fsol.meas);
% analytical solution
Block_R =  ll / ww / hh / scale/ conduc;
Contact_R = z_contact/(ww*hh)/scale^2;
% Contact R reflects z_contact / (width/scale)^2. Here we need to use
%  the scale, since this is not reflected in the size of the
%  FEM as created by the grid. This is different to the test_2d_resistor,
%  where the FEM is created scaled, so that the ww
%  don't need to be scaled by the scale parameter.
R = Block_R + 2*Contact_R;
V= current*R;
fprintf('Solver %s: %f\n', 'analytic', V);
fprintf('Solver %s: %f\n', 'analytic (no z_contact)', V - 2*Contact_R*current);
if 0 % OLD CODE
   mdl.solve = @np_fwd_solve;
   mdl.jacobian = @np_calc_jacobian;
else
   mdl.solve = @fwd_solve_1st_order;
   mdl.jacobian= @jacobian_adjoint;
end
mdl.misc.perm_sym= '{n}';
mdl.normalize_measurements = 0;
img= eidors_obj('image','3D rectangle', ...
      'elem_data', ones(size(mdl.elems,1),1) * conduc, ...
      'fwd_model', mdl);
fsol= fwd_solve(img);
fprintf('Solver %s: %f\n', fsol.name, fsol.meas);
% NOW CALCULATE THE ANALYTICAL JACOBIAN
if 0 % OLD CODE
   mdl.solve = @np_fwd_solve;
   mdl.jacobian = @np_calc_jacobian;
else
   mdl.solve = @fwd_solve_1st_order;
   mdl.jacobian= @jacobian_adjoint;
end
img.fwd_model = mdl;
img.elem_data= ones(n_el,1) * conduc ;
Jnp= calc_jacobian(img);
mdl.jacobian = @jacobian_perturb;
Jp1= calc_jacobian(img);
img.elem_data= ones(n_el,1) * conduc ;
Jp2= zeros(size(Jnp));
delta= 1e-8;
for i=1:n_el
   fsol_h= fwd_solve(img);
   img.elem_data(i) = img.elem_data(i) + delta;
   fsol_i= fwd_solve(img);
   Jp2(:,i) = (fsol_i.meas - fsol_h.meas)/delta;
end
mdl.solve = @fwd_solve_1st_order;
mdl.jacobian = @jacobian_adjoint;
Jaa= calc_jacobian(img);
fprintf('Jacobians: Cols by Jaa, Jnp, Jp1, Jp2\n');
JJ = [Jaa;Jnp;Jp1;Jp2];
disp(JJ(:,1:6))
% UNIT_TEST
unit_test_cmp('Jaa vs Jnp', Jaa, Jnp, 1e-6);
unit_test_cmp('Jaa vs Jp1', Jaa, Jp1, 1e-6);
unit_test_cmp('Jaa vs Jp2', Jaa, Jp2, 1e-3);
function cleaner_code
% Cleaner code using newer EIDORS helper functions (AA - dec 2018)
ll=5; ww=1; hh=1; z_contact= 1e-1; conduc= .13; current= 4; scale = .46;
mdl= rmfield(mk_grid_model([],0:ww,0:hh,0:ll), 'coarse2fine');
mdl.boundary= find_boundary(mdl.elems); mdl.gnd_node = 1;
mdl.electrode(1)=struct('z_contact', z_contact, 'nodes', ...
     find(mdl.nodes(:,3)==0));
mdl.electrode(2)=struct('z_contact', z_contact, 'nodes', ...
     find(mdl.nodes(:,3)==ll));
mdl.stimulation= stim_meas_list([1,2,1,2],2,current);
mdl.nodes = mdl.nodes * scale;
show_fem(mdl);
Block_R =  ll / ww / hh / scale/ conduc;
Contact_R = z_contact/(ww*hh)/scale^2;
Vs = current * (Block_R + 2*Contact_R);
vh = fwd_solve(mk_image(mdl, conduc));
unit_test_cmp('3D Resistor',Vs, vh.meas, 1e-10);