Description of calc_jacobian
Home > eidors > solvers > calc_jacobian.m
calc_jacobian
PURPOSE
CALC_JACOBIAN: calculate jacobian from an inv_model
SYNOPSIS
function J = calc_jacobian(fwd_model, img)
DESCRIPTION
 CALC_JACOBIAN: calculate jacobian from an inv_model
  J = calc_jacobian( img )
      calc Jacobian on img.fwd_model at conductivity given
      in image (fwd_model is for forward and reconstruction)
 The actual work is done by the jacobian calculator specified in
    img.fwd_model.jacobian, unless that field is numeric, in which case
    calc_jacobian returns its contents.
 For reconstructions on dual meshes, the interpolation matrix
    is defined as img.fwd_model.coarse2fine. This takes
    coarse2fine * x_coarse = x_fine
 If the underlying jacobian calculator doesn't understand dual
    meshes, then calc_jacobian will automatically postmultiply
    by fwd_model.coarse2fine.
 img       is an image structure, with 'elem_data' or
           'node_data' parameters
CROSS-REFERENCE INFORMATION
This function calls:
eidors_obj EIDORS_OBJ: maintains EIDORS internals
data_mapper DATA_MAPPER maps img.params data to elem or node data
mdl_normalize MDL_NORMALIZE Check or set the normalize_measurements flag on a model.
mk_circ_tank MK_CIRC_TANK: make a cylindrical tank FEM geometry in 2D or 3D
mk_common_model MK_COMMON_MODEL: make common EIT models
mk_image MK_IMAGE: create eidors image object
mk_stim_patterns MK_STIM_PATTERNS: create an EIDORS stimulation pattern structure
calc_jacobian CALC_JACOBIAN: calculate jacobian from an inv_model
fwd_model_parameters FWD_MODEL_PARAMETERS: data= fwd_solve_1st_order(fwd_model, image)
fwd_solve FWD_SOLVE: calculate data from a fwd_model object and an image
eidors_cache EIDORS_CACHE Control eidors caching
unit_test_cmp UNIT_TEST_CMP: compare matrices in eidors output
This function is called by:
left_divide [V] = LEFT_DIVIDE(E,I,tol,pp,V);
ab_tv_lagged_diff AB_TV_LAGGED_DIFF Lagged Diffusivity Inverse Solver
exponential_covar_prior EXPONENTIAL_COVAR_PRIOR image prior with exponential
np_inv_solve NP_INV_SOLVE inverse solver for Nick Polydorides EIDORS3D code
resistor_model DEMO to show really simple application of EIDORS framework
mono2stim MONO2SIM transform monopolar stimulation into another stim pattern
simulate_movement SIMULATE_MOVEMENT simulate small conductivity perturbations
calc_JiRtRJt [JiRtRJt,iRtRJt] = calc_JiRtRJt(inv_model, varargin)
calc_jacobian CALC_JACOBIAN: calculate jacobian from an inv_model
jacobian_adjoint_2p5d_1st_order JACOBIAN_ADJOINT_2P5D: J= jacobian_adjoint_2p5d_1st_order(img)
jacobian_adjoint_higher_order Find the Jacobian associated with an image (and forward model)
jacobian_apparent_resistivity jacobian_apparent_resistivity: Jacobian output as apparent resistivity
jacobian_elem2nodes JACOBIAN_ELEM2NODES: calculate Jacobian on Nodes from Elem solver
jacobian_movement JACOBIAN_MOVEMENT Computes the Jacobian matrix for conductivity and
jacobian_movement_halfspace JACOBIAN_MOVEMENT_PERTURB: J= jacobian_movement_perturb(img)
jacobian_movement_perturb JACOBIAN_MOVEMENT_PERTURB: J= jacobian_movement_perturb(img)
jacobian_perturb JACOBIAN_PERTURB: J= jacobian_perturb(fwd_model, img)
calc_GREIT_RM CALCULATE GREIT reconstruction matrix
calc_TSVD_RM CALC_TSVD_RM: Calculated truncated Jacobian SVD reconstruction matrix
calc_lambda_regtools % CALC_LAMBDA_REGTOOLS: Find optimal hyperparameter by the L-curve (LCC)
get_RM % GET_RM: obtains the reconstruction matrix from a given inverse model
inv_solve_TV_irls INV_SOLVE_TV_IRLS Iteratively Reweighted Least Squares inverse solver
inv_solve_abs_GN_constrain Do Gauss Netwon Method with barrier to ensure positvity of the con
inv_solve_abs_GN_prior INV_SOLVE_ABS_GN_PRIOR inverse solver (WITH DIFFERENT PRIOR AT ITERATION!!!!!)
inv_solve_abs_pdipm INV_SOLVE_ABS_PDIPM inverse solver for absolute data using Primal/Dual interior point method
inv_solve_conj_grad INV_SOLVE_CONJ_GRAD inverse solver based on the CG
inv_solve_core INV_SOLVE_CORE Solver using a generic iterative algorithm
inv_solve_diff_GN_one_step INV_SOLVE_DIFF_GN_ONE_STEP inverse solver using approach of Adler&Guardo 1996
inv_solve_diff_kalman INV_SOLVE_DIFF_KALMAN inverse solver for difference EIT
inv_solve_diff_pdipm INV_SOLVE_DIFF_PDIPM inverse solver for difference data using Primal/Dual interior point method
inv_solve_mcmc NP_INV_SOLVE inverse solver for Nick Polydorides EIDORS3D code
inv_solve_time_prior INV_SOLVE_TIME_PRIOR inverse solver to account for time differences
inv_solve_trunc_iterative INV_SOLVE_TRUNC_ITERATIVE using Morozov truncated iteration
nodal_solve NODAL_SOLVE inverse solver using approach of Adler&Guardo 1996
primaldual_tvrecon_lsearch [rs,x]=primaldual_tvrecon_lsearch(inv_mdl, vmeas, ...
prior_exponential_covar PRIOR_EXPONENTIAL_COVAR image prior with exponential
prior_noser PRIOR_NOSER calculate image prior
calc_data_prior_test Verify dataprior:
demo_real_test2 Perform tests based on the demo_real function with new structs
demo_real_test3 Perform tests based on the demo_real function with new structs
test_2d_resistor Create 2D model of a cylindrical resistor
test_3d_resistor Create 3D model of a Rectangular resistor
test_performance TEST_PERFORMANCE: test of difference reconstruction algorithms
test_performance_img TEST_PERFORMANCE: test of difference reconstruction algorithms
SUBFUNCTIONS
function cache_obj= jacobian_cache_params(fwd_model, img);
function fwd_model_check(fmdl)
function do_unit_test
function run_jacobian_test(mdl, delta, testvec,tol);
function mdl= test_aa_mdl2;
function mdl= test_aa_mdl3;
function mdl= test_np_mdl;
function mdl= test_ms_mdl;
SOURCE CODE
function J = calc_jacobian(fwd_model, img)
% CALC_JACOBIAN: calculate jacobian from an inv_model
%
%  J = calc_jacobian(img)
%      calc Jacobian on img.fwd_model at conductivity given
%      in image (fwd_model is for forward and reconstruction)
%
% The actual work is done by the jacobian calculator specified in
%    img.fwd_model.jacobian, unless that field is numeric, in which case
%    calc_jacobian returns its contents.
%
% For reconstructions on dual meshes, the interpolation matrix
%    is defined as img.fwd_model.coarse2fine. This takes
%    coarse2fine * x_coarse = x_fine
%
% If the underlying jacobian calculator doesn't understand dual
%    meshes, then calc_jacobian will automatically postmultiply
%    by fwd_model.coarse2fine.
%
% img       is an image structure, with 'elem_data' or
%           'node_data' parameters
% (C) 2005-08 Andy Adler. License: GPL version 2 or version 3
% $Id: calc_jacobian.m 6716 2024-04-02 17:59:16Z aadler $
if ischar(fwd_model) && strcmp(fwd_model,'UNIT_TEST'); do_unit_test; return; end
if nargin == 1
   img= fwd_model;
else
   warning('EIDORS:DeprecatedInterface', ...
      ['Calling CALC_JACOBIAN with two arguments is deprecated and will cause' ...
       ' an error in a future version. First argument ignored.']);
end
ws = warning('query','EIDORS:DeprecatedInterface');
warning off EIDORS:DeprecatedInterface
try
   fwd_model= img.fwd_model;
catch
   error('CALC_JACOBIAN requires an eidors image structure');
end
fwd_model_check(fwd_model);
if isnumeric(fwd_model.jacobian)             % we have the Jacobian matrix
   J = fwd_model.jacobian;
else                                         % we need to calculate
   copt.cache_obj= jacobian_cache_params( fwd_model, img );
   copt.fstr = 'jacobian';
   try
       fwd_model.jacobian = str2func(fwd_model.jacobian);
   end
   J = eidors_cache(fwd_model.jacobian, {fwd_model, img}, copt);
end
if isfield(fwd_model,'coarse2fine')
   c2f= fwd_model.coarse2fine;
   if size(J,2)==size(c2f,1)
%     calc_jacobian did not take into account the coarse2fine
      J=J*c2f;
   end
end
warning(ws.state, 'EIDORS:DeprecatedInterface');
% Make the Jacobian only depend on
function cache_obj= jacobian_cache_params(fwd_model, img);
   img = data_mapper(img);
   if isfield(img, 'elem_data')
      cache_obj = {fwd_model, img.elem_data, img.current_params};
   elseif isfield(img, 'node_data')
      cache_obj = {fwd_model, img.node_data, img.current_params};
   else
      error('calc_jacobian: execting elem_data or node_data in image');
   end
function fwd_model_check(fmdl)
   try; if fmdl.jacobian_dont_check
      return
   end; end
   pp = fwd_model_parameters(fmdl); % they cache, so no problem
   if pp.n_elec == 0
       error('Cannot calculate Jacobian. No electrodes found.');
   end
   if pp.n_stim == 0
       error('Cannot calculate Jacobian. No stimulation found.');
   end
   if pp.n_meas == 0
       error('Cannot calculate Jacobian. No measurements found.');
   end
function do_unit_test
    delta = 1e-6;
    testvec= [5,20,40,130];
    mdl= test_aa_mdl2;
    run_jacobian_test( mdl, delta, testvec );
    mdl = mdl_normalize(mdl,1); mdl.name = [mdl.name,':normalize'];
    run_jacobian_test( mdl, delta, testvec );
    mdl= test_aa_mdl3;
    run_jacobian_test( mdl, delta, testvec );
    mdl = mdl_normalize(mdl,1); mdl.name = [mdl.name,':normalize'];
    run_jacobian_test( mdl, delta, testvec );
    warning('off','EIDORS:deprecated');
    mdl= test_np_mdl;
    % Need lower tol because np models use a solver with lower tol
    run_jacobian_test( mdl, delta, testvec, 1e-3 );
    mdl = mdl_normalize(mdl,1); mdl.name = [mdl.name,':normalize'];
    run_jacobian_test( mdl, delta, testvec, 1e-3 );
function run_jacobian_test(mdl, delta, testvec,tol);
    img= mk_image(mdl,1);
    homg_data=fwd_solve( img);
    J= calc_jacobian( img );
    if nargin<4;tol= 1e-5;end
    tol = tol*std(J(:));
    % J = dF/dx = [F(x+d)  - F(x)]/d
    sumdiff= 0;
    bkgnd_elem_data= img.elem_data;
    for testelem = testvec
       img.elem_data= bkgnd_elem_data;
       img.elem_data(testelem)= bkgnd_elem_data(testelem)+delta;
       inh_data=fwd_solve( img);
       if mdl_normalize(mdl)
          simJ= 1/delta* (inh_data.meas ./ homg_data.meas - 1);
       else
          simJ= 1/delta* (inh_data.meas-homg_data.meas);
       end
       plot([J(:,testelem) simJ]);
       sumdiff = sumdiff + std( J(:,testelem) - simJ );
    end
    dif= sumdiff/length(testvec);
    unit_test_cmp(['Jacobian calc: ',mdl.name],sumdiff/length(testvec),0,tol);
function mdl= test_aa_mdl2;
    n_elec= 16;
    n_rings= 1;
    options = {'no_meas_current','no_rotate_meas'};
    params= mk_circ_tank(8, [], n_elec);
    params.stimulation= mk_stim_patterns(n_elec, n_rings, '{ad}','{ad}', ...
                                options, 10);
    params.solve=      'fwd_solve_1st_order';
    params.system_mat= 'system_mat_1st_order';
    params.jacobian=   'jacobian_adjoint';
    params.normalize_measurements = 0;
    mdl = eidors_obj('fwd_model', params);
    mdl.name= 'AA_1996 mdl';
function mdl= test_aa_mdl3;
    i_mdl = mk_common_model('b3cz2',16);
    mdl= i_mdl.fwd_model;
    mdl.name= 'AA_1996 mdl';
    mdl.solve=      'fwd_solve_1st_order';
    mdl.system_mat= 'system_mat_1st_order';
    mdl.jacobian=   'jacobian_adjoint';
function mdl= test_np_mdl;
    i_mdl = mk_common_model('n3r2',[16,2]);
    mdl= i_mdl.fwd_model;
    mdl.name=     'NP_2003 mdl';
    mdl.solve=      'np_fwd_solve';
    mdl.system_mat= 'np_calc_system_mat';
    mdl.jacobian=   'np_calc_jacobian';
function mdl= test_ms_mdl;
    i_mdl = mk_common_model('n3r2',16);
    mdl= i_mdl.fwd_model;
    mdl.name=       'MS_2005 mdl';
    mdl.solve=      'np_fwd_solve';
    mdl.system_mat= 'np_calc_system_mat';
    mdl.jacobian=   'ms_calc_jacobian';