Description of citeme
Home > eidors > tools > citeme.m
citeme
PURPOSE
CITEME Display citation requests
SYNOPSIS
function citeme(fname)
DESCRIPTION
CITEME Display citation requests
 Processes CITATION_REQUEST blocks in the first comment block of a
 function. Must be called at citeme(mfilename).
 Citation requests are displayed only once per session, and look like
 this:
 CITATION_REQUEST:
 AUTHOR: Author Name, Author Name, Author Name, Author Name, Author Name,
 Author Name and Author Name
 TITLE: A very long and complicated title that necessarily goes over
 several lines
 JOURNAL: A renowned international journal that is so full of itself that
 its name is very long
 VOL: V
 NUM: N
 YEAR: 2013
 PAGE: 1-10
 LINK: http://www.journal-website.com/dir/dir/some_strange_numbers_and_
       letters_that_goes_over_several_lines
 PDF: ftp://myserver.com/paper1.pdf
 DOI: 1234/qwre/123
 PUBMED: 12321345
 ARXIV:  0706.0001
 CITATION_REQUEST:
 AUTHOR: Author Name
 TITLE: A 2nd paper
 JOURNAL: Jounral wth a short name
 VOL: V
 NUM: N
 YEAR: 2013
 PAGE: 1-10
 A CITATION_REQUEST block is terminated by an empty line.
 The order of fields is irrelevant. All fields are optional.
 Multiple CITATION_REQUEST blocks are supported.
 See also STARTUP
CROSS-REFERENCE INFORMATION
This function calls:
citeme CITEME Display citation requests
This function is called by:
ng_mk_extruded_model NG_MAKE_EXTRUDED_MODEL: create extruded models using netgen
mk_GREIT_model MK_GREIT_MODEL: make EIDORS inverse models using the GREIT approach
mk_head_model_adult MK_HEAD_MODEL_ADULT Adult head model
mk_lung_image MK_LUNG_IMAGE create an image with lung and heart contrasts from a model
mk_thorax_model_bp3d MK_THORAX_MODEL_BP3D Torso model based on BodyParts3D
mk_thorax_model_grychtol2016a Builds the male thorax models from Grychtol, Müller and Adler (2016)
place_elec_on_surf PLACE_ELEC_ON_SURF Place electrodes on the surface of a model
system_mat_instrument SYSTEM_MAT_INSTRUMENT:
calc_image_SNR % CALC_IMAGE_SNR: Calculates the signal-to-noise ratio (SNR) in the image
calc_lambda_regtools % CALC_LAMBDA_REGTOOLS: Find optimal hyperparameter by the L-curve (LCC)
inv_solve_d_bar D-Bar reconstruction
citeme CITEME Display citation requests
SUBFUNCTIONS
function str = parse_block(T)
function str = pretty_print(cite)
function cite = empty_cite
SOURCE CODE
function citeme(fname)
%CITEME Display citation requests
% Processes CITATION_REQUEST blocks in the first comment block of a
% function. Must be called at citeme(mfilename).
% Citation requests are displayed only once per session, and look like
% this:
%
% CITATION_REQUEST:
% AUTHOR: Author Name, Author Name, Author Name, Author Name, Author Name,
% Author Name and Author Name
% TITLE: A very long and complicated title that necessarily goes over
% several lines
% JOURNAL: A renowned international journal that is so full of itself that
% its name is very long
% VOL: V
% NUM: N
% YEAR: 2013
% PAGE: 1-10
% LINK: http://www.journal-website.com/dir/dir/some_strange_numbers_and_
%       letters_that_goes_over_several_lines
% PDF: ftp://myserver.com/paper1.pdf
% DOI: 1234/qwre/123
% PUBMED: 12321345
% ARXIV:  0706.0001
%
% CITATION_REQUEST:
% AUTHOR: Author Name
% TITLE: A 2nd paper
% JOURNAL: Jounral wth a short name
% VOL: V
% NUM: N
% YEAR: 2013
% PAGE: 1-10
%
% A CITATION_REQUEST block is terminated by an empty line.
% The order of fields is irrelevant. All fields are optional.
% Multiple CITATION_REQUEST blocks are supported.
%
% See also STARTUP
if ischar(fname) && strcmp(fname, 'UNIT_TEST')
    citeme(mfilename);
    return;
end
cm = warning('query','EIDORS:CITEME'); % one would think this is supported
cf = warning('query',sprintf('EIDORS:CITEME:%s',fname));
if strcmp(cm.state, 'off') || strcmp(cf.state, 'off');
    return
end
h = help(fname);
s = strfind(h,'CITATION_REQUEST:');
if isempty(s), return, end;
T = textscan(h(s(1):end),'%s','delimiter','\n');
T = T{1};
starts = 1;
if numel(s) > 1
   starts = find(strcmp(T, 'CITATION_REQUEST:'));
end
empty_lines = find(cellfun(@isempty,T));
if numel(empty_lines) < numel(starts)
   %happens if the CITATION_REQUEST runs to the end of T (no empty line)
   empty_lines(end+1) = numel(T);
end
s = s - s(1) + 1;
for i = 1:numel(s)
   block = T(starts(i):empty_lines(find(empty_lines>starts(i), 1, 'first')));
   citation{i} = parse_block(block);
end
str = sprintf('\n%s\n',citation{:});
ws = warning('off', 'backtrace');
idstr = sprintf('EIDORS:CITEME:%s',fname);
stars(1:80) = '=';
msg = sprintf('\n%s\nIf you use %s in a publication, please cite:\n', stars,upper(fname));
warning(idstr,[msg str stars]);
if 0
   disp('Press any key to continue...');
   pause
else
   fprintf('Continuing in  ');
   for i = 2:-1:1
      fprintf('\b%d',i);
      pause(1);
   end
   fprintf('\b0\n');
end
warning(ws.state, 'backtrace');
if ~strcmp(fname,'citeme')
    warning('off',idstr); % only show once per session
end
function str = parse_block(T)
line = 2;
lastfld = [];
cite = empty_cite;
while line <= numel(T) && ~isempty(strtrim(T{line}))
    [tok rest] = strtok(T{line});
    if strfind(tok,':');
            fld = lower(tok(1:end-1));
            cite.(fld) = strtrim(rest);
            lastfld = fld;
    elseif ~isempty(lastfld)
        cite.(lastfld) = sprintf('%s %s%s', cite.(lastfld), tok, rest);
    else
        error('Error processing citation request of file %s',fname);
    end
    line = line + 1;
end
flds = {'link','pdf','pubmed','arxiv','doi'};
for i = 1:numel(flds)
    cite.(flds{i})(isspace(cite.(flds{i}))) = [];
end
str = pretty_print(cite);
function str = pretty_print(cite)
str = sprintf('%s (%s) "%s"',...
    cite.author,cite.year,cite.title);
if ~isempty(cite.link)
    str = sprintf('%s <a href="matlab: web %s -browser">%s</a>%s', str, cite.link, cite.journal);
else
    str = sprintf('%s %s',str, cite.journal);
end
if ~isempty(cite.vol)
    str = sprintf('%s %s',str,cite.vol);
end
if ~isempty(cite.num)
    if ~isempty(cite.vol)
        str = sprintf('%s(%s)',str, cite.num);
    else
        str = sptrinf('%s %s',str, cite.num);
    end
end
if ~isempty(cite.page)
    str = sprintf('%s: %s',str, cite.page);
end
if ~isempty(cite.pdf)
    str = sprintf('%s <a href="matlab: web %s -browser">PDF</a>',str, cite.pdf);
end
if ~isempty(cite.doi)
    str = sprintf('%s DOI:<a href="matlab: web http://dx.doi.org/%s -browser">%s</a>',...
                    str, cite.doi,cite.doi);
end
if ~isempty(cite.pubmed)
    str = sprintf('%s PubMed:<a href="matlab: web http://www.ncbi.nlm.nih.gov/pubmed/%s -browser">%s</a>',...
                    str, cite.pubmed,cite.pubmed);
end
if ~isempty(cite.arxiv)
    str = sprintf('%s arXiv:<a href="matlab: web http://arxiv.org/abs/%s -browser">%s</a>',...
                    str, cite.doi,cite.doi);
end
str = strtrim(str);
sp = strfind(str,' ');
tp1 = strfind(str,'<');
tp2 = strfind(str,'>');
sp = [sp length(str)];
rsp = sp; % real spaces
idx = false(size(sp));
for i = 1:length(tp1)
    nidx =  rsp>tp1(i) & rsp<tp2(i);
    idx = idx | nidx;
    sp(rsp>tp1(i)) = sp(rsp>tp1(i)) - (tp2(i) + 2- tp1(i));
end
sp(idx) = [];
rsp(idx) = [];
[jnk, nl] = unique(floor(sp/82),'last');
nl = rsp(nl);
nl(nl==length(str)) = [];
str(nl) = sprintf('\n');
function cite = empty_cite
cite.author = [];
cite.year   = [];
cite.journal= [];
cite.title  = [];
cite.vol    = [];
cite.num    = [];
cite.page   = [];
cite.link   = [];
cite.pdf    = [];
cite.doi    = [];
cite.pubmed = [];
cite.arxiv  = [];