Description of calc_slices
Home > eidors > graphics > matlab > calc_slices.m
calc_slices
PURPOSE
calc_slices (img, levels, clim) show slices at levels of an
SYNOPSIS
function rimg = calc_slices(img, levels);
DESCRIPTION
 calc_slices (img, levels, clim  ) show slices at levels of an
             using a fast rendering algorithm
 img    = EIDORS image struct, or array of I images
 levels = any level definition accepted by level_model_slice
 PARAMETERS:
   img.calc_slices.filter % Filter to be applied to images
      Example:    img.calc_slices.filter = ones(3)/9
   img.calc_slices.scale  % Scaling to apply to images
   img.get_img_data.frame_select = which frames of image to display
 rimg= np x np x I x L where np is 128 by default
   np can be adjusted by calc_colours('npoints')
     or by setting
   img.fwd_model.mdl_slice_mapper.{npx, npy}
        see help of mdl_slice_mapper for more options
 See also: LEVEL_MODEL_SLICE
CROSS-REFERENCE INFORMATION
This function calls:
eidors_msg EIDORS_MSG eidors progress and status messages
calc_colours [colours,scl_data]= calc_colours(img, set_value, do_colourbar)
calc_slices calc_slices (img, levels, clim) show slices at levels of an
level_model_slice LEVEL_MODEL_SLICE - level 3D points for slicing at z=0
mdl_slice_mapper MDL_SLICE_MAPPER: map pixels to FEM elements or nodes
data_mapper DATA_MAPPER maps img.params data to elem or node data
interp_mesh INTERP_MESH: calculate interpolation points onto mdl elements
mdl_dim MDL_DIM: dimension of model space (are nodes in 2D or 3D space)
mk_common_model MK_COMMON_MODEL: make common EIT models
mk_image MK_IMAGE: create eidors image object
calc_jacobian_bkgnd CALC_JACOBIAN_BKGND: calculate background image around
get_img_data GET_IMG_DATA: get parameter data from eidors image object
unit_test_cmp UNIT_TEST_CMP: compare matrices in eidors output
This function is called by:
calc_posn_resolution CALC_POSN_RESOLUTION: calculate posn and resolution of a target
eval_GREIT_fig_merit EVAL_GREIT_FIG_MERIT: calculate GREIT figures of merit for images
solve_RM_2Dslice SELECT_RM_SLICE: cut slices out of an inverse model with a
animate_reconstructions animate_reconstructions(fname, imgs);
calc_slices calc_slices (img, levels, clim) show slices at levels of an
mk_mosaic MK_MOSAIC Arrange multidimensional image matrix for display.
show_slices out_img = show_slices (img, levels) show slices at levels of an
eidors_saveimg EIDORS saveimg - save reconstructed image files in formats
igt2img IGT2IMG constructs an EIDORS IMG struct from an IGT frames-by-912 matrix.
img2igt IMG2IGT returns an IGT-compatible image matrix from any EIDORS
write_ibex_mat WRITE_IBEX_MAT: write images to ibex mat file format
map_RM_slice map_RM_slice - map a 3D reconstruction matrix to an arbitrary 2D slice
mk_GREIT_model MK_GREIT_MODEL: make EIDORS inverse models using the GREIT approach
mk_pixel_slice MK_PIXEL_SLICE create a pixel model to reconstruct on
select_RM_slice SELECT_RM_SLICE: cut slices out of an inverse model with a
calc_image_SNR % CALC_IMAGE_SNR: Calculates the signal-to-noise ratio (SNR) in the image
test_colour_direction Test colour mapping
test_performance TEST_PERFORMANCE: test of difference reconstruction algorithms
test_performance_img TEST_PERFORMANCE: test of difference reconstruction algorithms
SUBFUNCTIONS
function rimg = calc_this_slice(img, levels, np)
function rimg= calc_image_nearestnodes(node_data, fwd_model)
function rimg= calc_image_nodes(node_data, fwd_model)
function rimg= calc_image_elems(elem_data, fwd_model)
function rimg = filter_image(rimg, filt);
function do_unit_test
SOURCE CODE
function rimg = calc_slices(img, levels);
% calc_slices (img, levels, clim) show slices at levels of an
%             using a fast rendering algorithm
% img    = EIDORS image struct, or array of I images
% levels = any level definition accepted by level_model_slice
%
% PARAMETERS:
%   img.calc_slices.filter % Filter to be applied to images
%      Example:    img.calc_slices.filter = ones(3)/9
%   img.calc_slices.scale  % Scaling to apply to images
%   img.get_img_data.frame_select = which frames of image to display
%
% rimg= np x np x I x L where np is 128 by default
%
%   np can be adjusted by calc_colours('npoints')
%     or by setting
%   img.fwd_model.mdl_slice_mapper.{npx, npy}
%        see help of mdl_slice_mapper for more options
%
% See also: LEVEL_MODEL_SLICE
% (C) 2006-2024 Andy Adler and Bartek Grychtol.
% License: GPL version 2 or version 3
% $Id: calc_slices.m 6964 2024-09-27 13:30:40Z aadler $
if ischar(img) && strcmp(img,'UNIT_TEST'); do_unit_test; return; end
np = calc_colours('npoints');
try np = img(1).calc_colours.npoints; end
if nargin < 2, levels = []; end
if isfield(img, 'calc_slices') && isfield(img.calc_slices, 'levels')
    warning('EIDORS:CALC_SLICES:DeprecatedInterface', ...
        ['Ingoring deprecated img.calc_slices.levels definition. '...
        'Use img.fwd_model.mdl_slice_mapper.level instead. '...
        'See help level_model_slice for valid inputs.'])
    img.calc_slices = rmfield(img.calc_slices, 'levels');
end
img = data_mapper(img);
% Assume all fwd_models are same dimension (all 3D or 2D no mixed dims)
if mdl_dim(img(1))==2
    if nargin>1
        eidors_msg('Specified levels ignored for 2D FEM', 4);
    end
    if isfield(img(1).fwd_model,'mdl_slice_mapper') && isfield(img(1).fwd_model.mdl_slice_mapper, 'level')
        eidors_msg('mdl_slice_mapper.level definition ignored for 2D FEM',4);
        for i = 1:numel(img)
            img(i).fwd_model.mdl_slice_mapper = rmfield(img(i).fwd_model.mdl_slice_mapper,'level');
        end
    end
    levels= [Inf,Inf,0];
end
warnStruct = warning('query','EIDORS:calc_slices:level_conflict');
rimg = [];
for i=1:length(img)
   rimg = cat(3, rimg, calc_this_slice( img(i), levels, np) );
end
warning(warnStruct)
function rimg = calc_this_slice(img, levels, np)
    % If scalar levels then we just create that many cut planes on z-dimension
    fwd_model = img.fwd_model;
    if ~isfield(fwd_model,'mdl_slice_mapper') || ...
          nnz(isfield(fwd_model.mdl_slice_mapper, {'x_pts', 'npoints', 'npx', 'resolution'})) == 0
        fwd_model.mdl_slice_mapper.npoints = np;
    end
    if isfield(fwd_model.mdl_slice_mapper, 'level')
       if ~isempty(levels)
          warning('EIDORS:calc_slices:level_conflict',...
             'Ignoring provided level definition. Using mdl_slice_mapper.level instead.');
          % only warn once
          warning('off', 'EIDORS:calc_slices:level_conflict');
       else
          eidors_msg('Using level definition from the mdl_slice_mapper.level field.', 3);
       end
       levels = fwd_model.mdl_slice_mapper.level;
    end
    if isempty(levels)
       z = max(img.fwd_model.nodes(:,3)) - min(img.fwd_model.nodes(:,3));
       levels = [Inf Inf z/2];
       eidors_msg('calc_slices: no levels specified, using mid-z xy plane',2);
    end
    nodes = {fwd_model.nodes};
    if size(fwd_model.nodes,2)==3 && size(fwd_model.elems,2) > 3
        nodes = level_model_slice(fwd_model.nodes, levels, 'all');
        % we'll level by replacing nodes. Disable.
        lvl = struct('rotation_matrix',eye(3), 'centre', zeros(1,3));
        fwd_model.mdl_slice_mapper.level = lvl;
    end
    [data, n_images] = get_img_data(img);
    if ~any(isfield(img, {'elem_data', 'node_data'}))
       error('img does not have a data field');
    end
    n_levels = numel(nodes);
    for lev_no = fliplr(1:n_levels)
        fwd_model.nodes = nodes{lev_no};
        if isfield(img,'elem_data')
          rimg(:,:,:,lev_no) = calc_image_elems( data, fwd_model);
        elseif isfield(img,'node_data')
          rimg(:,:,:,lev_no) = calc_image_nodes( data, fwd_model);
        end
    end
    % FILTER IMAGE
    try
        filt = img.calc_slices.filter;
    catch
        filt = 1;
    end
    try
        scal = img.calc_slices.scale;
    catch
        scal = 1;
    end
    filt = scal * ( filt/sum(filt(:)) );
    rimg = filter_image(rimg, filt);
% Calculate an image by mapping it onto the node_ptr matrix
% This makes a blocky image to nearest node -> no longer used
function rimg= calc_image_nearestnodes(node_data, fwd_model)
   node_ptr = mdl_slice_mapper( fwd_model, 'node' );
   backgnd= NaN;
   n_images= size(node_data,2);
   rval= [backgnd*ones(1,n_images); node_data];
   rimg= reshape( rval(node_ptr+1,:), [size(node_ptr), n_images]);
% Calculate an image by interpolating it onto the elem_ptr matrix
function rimg= calc_image_nodes(node_data, fwd_model)
   nd_interp= mdl_slice_mapper( fwd_model, 'nodeinterp' );
   elem_ptr = mdl_slice_mapper( fwd_model, 'elem' );
   [sx,sy]= size(elem_ptr);
   node_ptr = fwd_model.elems; node_ptr = [0*node_ptr(1,:);node_ptr];
   node_ptr = reshape( node_ptr( elem_ptr+1, :), sx, sy, []);
   n_images = size(node_data,2);
   rimg= zeros(sx, sy, n_images);
   backgnd= NaN;
   for ni = 1:n_images
     znd = [backgnd;node_data(:,ni)]; % add NaN for background
     rimg(:,:,ni) = sum( znd(node_ptr+1) .* nd_interp, 3);
   end
% Calculate an image by mapping it onto the elem_ptr matrix
function rimg= calc_image_elems(elem_data, fwd_model)
   elem_ptr = mdl_slice_mapper( fwd_model, 'elem');
   backgnd= NaN;
   n_images= size(elem_data,2);
   rval= backgnd*ones(size(elem_data)+[1,0]);
   rval(2:end,:) = elem_data;
   rimg= reshape( rval(elem_ptr+1,:), [size(elem_ptr), n_images]);
function  rimg = filter_image(rimg, filt);
   %%% Total MATLAB BS )(*&#$)(*#&@
   %%% the && operator used to short circuit. Now it doesn't
   %%% How the (*&)(*& can anyone take this language seriously
   % all(size(filt*scal) == [1,1]) && filt*scal == 1
   if all(size(filt)==1) if filt == 1; return; end ; end
   [sz1,sz2,sz3,sz4] = size(rimg);
   for j1 = 1:sz3; for j2 = 1:sz4;
      rsl = rimg(:,:,j1,j2);
      rna = isnan(rsl);
      rsl(rna) = 0;
      rsl = conv2(rsl, filt, 'same');
      rsl(rna) = NaN;
      rimg(:,:,j1,j2) = rsl;
   end; end
function do_unit_test
   img = mk_image( mk_common_model('a2c2',8));
   img.calc_colours.npoints = 8;
   imc = calc_slices(img);
   imt = NaN*ones(8); imt(2:7,2:7) = 1; imt(3:6,:) = 1; imt(:,3:6) = 1;
   unit_test_cmp('cs 2d 1', imc, imt);
   imn = rmfield(img,'elem_data');
   imn.node_data = ones(size(imn.fwd_model.nodes,1),1);
   imc = calc_slices(imn);
   unit_test_cmp('cs 2d 2', imc, imt, 1e-14);
   img.elem_data(1:4) = 2;
   imc = calc_slices(img);
   imt(4:5,4:5) = 2;
   unit_test_cmp('cs 2d 3', imc, imt);
   imn.node_data(1:5) = 2;
   imc = calc_slices(imn);
   imt(3:6,3:6) = 1; imt(4:5,3:6) = 1.292893218813452;
   imt(3:6,4:5) = 1.292893218813452; imt(4:5,4:5) = 2;
   unit_test_cmp('cs 2d 4', imc, imt, 1e-14);
   imn.node_data(:) = 1; imn.node_data(1) = 4;
   imc = calc_slices(imn);
   imt(3:6,3:6) = 1; imt(4:5,4:5) = 1.878679656440358;
   unit_test_cmp('cs 2d 5', imc, imt, 1e-14);
   imn.calc_colours.npoints = 7;
   imc = calc_slices(imn);
   imt = NaN*ones(7); imt(3:5,:) = 1; imt(:,3:5)= 1; imt(2:6,2:6)= 1;imt(4,4) = 4;
   unit_test_cmp('cs 2d 6', imc, imt, 1e-14);
% 3D Tests
   img = calc_jacobian_bkgnd( mk_common_model('n3r2',[16,2]));
   xyz = interp_mesh(img);
   img.calc_colours.npoints = 8;
   imn = calc_slices(img,[inf,inf,1]);
   imt = NaN*ones(8); imt(3:6,:) = 1; imt(:,3:6) = 1; imt(2:7,2:7) = 1;
   unit_test_cmp('cs 3d 1', imn, imt);
   imgx= img;
   imgx.elem_data(xyz(:,3)>1.5) = 2;
   imn = calc_slices(imgx,[inf,inf,0.5;inf,inf,2.5]);
   unit_test_cmp('cs 3d 2', imn, cat(4,imt,2*imt));
   imgx.elem_data = imgx.elem_data*[1,2,3];
   imn = calc_slices(imgx,[inf,inf,0.5]);
   imtx = cat(3,imt,2*imt,3*imt);
   unit_test_cmp('cs 3d 3', imn, imtx);
   imn = calc_slices(imgx,[inf,inf,0.5;inf,inf,2.5]);
   unit_test_cmp('cs 3d 3', imn, cat(4,imtx,2*imtx));
   imgx.fwd_model.mdl_slice_mapper=struct('x_pts',(-1:1)/2,'y_pts',(-1:1)/2, ...
         'level',[inf,inf,0.5;inf,inf,2.5]);
   imn = calc_slices(imgx);
   imt = ones(3); imtx = cat(3,imt,2*imt,3*imt);
   unit_test_cmp('cs 3d 3', imn, cat(4,imtx,2*imtx));
   img.calc_colours.npoints = 12;
   imn = calc_slices(img,[inf,0,inf]);
   imt = NaN*ones(12); imt(:,3:10) = 1;
   unit_test_cmp('cs 3d 4', imn, imt);
   % Should have no effect
   img.fwd_model.nodes(:,3) = img.fwd_model.nodes(:,3)-1;
   imn = calc_slices(img,[inf,0,inf]);
   unit_test_cmp('cs 3d 5', imn, imt);
   % Default level
   imt = calc_slices(img, [inf inf 0.5]);
   imn = calc_slices(img);
   unit_test_cmp('default', imn, imt);
    % Default level
   img.fwd_model.mdl_slice_mapper.level = [inf inf 0.5];
   imn = calc_slices(img);
   unit_test_cmp('no message', imn, imt);
   % Warning test
   warning('off', 'EIDORS:calc_slices:level_conflict');  %don't need to print
   [old, old_id] = lastwarn;
   lastwarn('','');
   img.fwd_model.mdl_slice_mapper.level = [inf,inf, 1.5];
   imt = calc_slices(img,[inf,inf, .5]);
   [~,id] = lastwarn;
   lastwarn(old, old_id);
   warning('on', 'EIDORS:calc_slices:level_conflict');
   unit_test_cmp('warning', id, 'EIDORS:calc_slices:level_conflict');
% multi image struct
   img = mk_image( mk_common_model('a2c2',8));
   img.calc_colours.npoints = 8;
   img(2) = img;
   imc = calc_slices(img);
   imt = NaN*ones(8); imt(3:6,:) = 1; imt(:,3:6) = 1; imt(2:7,2:7) = 1;
   unit_test_cmp('cs mult 1', imc, cat(3,imt,imt));
   imgb = mk_image( mk_common_model('b2c2',8));
   imgb.calc_colours.npoints = 8;
   img(3)=imgb;
   imc = calc_slices(img);
   unit_test_cmp('cs mult 2', imc, cat(3,imt,imt,imt));
   imdl = mk_common_model('c2t2',16);
   img = mk_image(imdl,1);
   imc = calc_slices(img);
   unit_test_cmp('size e  1', size(imc), [64,64]);
   img.calc_colours.npoints = 40;
   imc = calc_slices(img);
   unit_test_cmp('size e  2', size(imc), [40,40]);
   img.fwd_model.mdl_slice_mapper.npx = 22;
   img.fwd_model.mdl_slice_mapper.npy = 32;
   imc = calc_slices(img);
   unit_test_cmp('size e  3', size(imc), [32,22]);
   img.fwd_model = rmfield(img.fwd_model,'mdl_slice_mapper');
   img.fwd_model.mdl_slice_mapper.x_pts = linspace(-150,150,20);
   img.fwd_model.mdl_slice_mapper.y_pts =-linspace(-150,150,23);
   imc = calc_slices(img);
   unit_test_cmp('size e  4', size(imc), [23,20]);
   img = rmfield(img,'elem_data');
   img.node_data =  ones(size(img.fwd_model.nodes,1),1);
   img.node_data =  (1:size(img.fwd_model.nodes,1))';
   img.fwd_model = rmfield(img.fwd_model,'mdl_slice_mapper');
   imc = calc_slices(img);
   unit_test_cmp('size n  1', size(imc), [40,40]);
   im2= img;
   im2.node_data =  ones(size(img.fwd_model.nodes,1),5);
   imc = calc_slices(im2);
   unit_test_cmp('size n x5', size(imc), [40,40,5]);
   im2.get_img_data.frame_select = 2:3;
   imc = calc_slices(im2);
   unit_test_cmp('size n x2', size(imc), [40,40,2]);
   img.fwd_model.mdl_slice_mapper.x_pts = linspace(-150,150,20);
   img.fwd_model.mdl_slice_mapper.y_pts =-linspace(-150,150,23);
   imc = calc_slices(img);
   unit_test_cmp('size n  2', size(imc), [23,20]);