Description of eidors_obj
Home > eidors > eidors_obj.m
eidors_obj
PURPOSE
EIDORS_OBJ: maintains EIDORS internals
SYNOPSIS
function [obj_id, extra_out] = eidors_obj(type,name, varargin)
DESCRIPTION
 EIDORS_OBJ: maintains EIDORS internals
 USAGE: to get eidors_version
     version = eidors_obj('eidors_version')
 USAGE: to get interpreter version:
     version = eidors_obj('interpreter_version')
 USAGE: to get path to EIDORS:
     path = eidors_obj('eidors_path');
 USAGE: (for developers) to create a new eidors object:
     obj = eidors_obj('fwd_model','obj name','nodes',N,'elems',E,...)
     obj = eidors_obj('fwd_model',mdl_struct,'name','obj name',..)
     obj = eidors_obj('fwd_model',mdl_struct);
 will return an object of type 'fwd_model' with standardized field order.
 USAGE: (for developers) to set fields on existing objects:
     obj = eidors_obj('set',obj,'name','obj name',...);
     obj = eidors_obj('set',obj);
 will return an object with standardized field order.
 USAGE: to cache values (not recommended)
            obj_id = eidors_obj('set-cache',obj, cachename,value, [time])
     [obj, obj_id] = eidors_obj('get-cache',obj, cachename)
 this will get or set the values of cached properties of the object.
    example: % set jacobian
        obj_id = eidors_obj('set-cache',cache_obj, 'jacobian', J);
    example: % get jacobian or '[]' if not set
        [J, obj_id] = eidors_obj('get-cache',cache_obj, 'jacobian');
 It is recommended to combine in cache_obj the minimum set of variables on
 which the value to be cached depends.
    example: % cache_obj for jacobian
        cache_obj = {img.fwd_model.nodes, img.fwd_model.elems ...
                     img.elem_data, img.fwd_model.jacobian}
 NOTE that rather than directly using eidors_obj to set and get cache, it
 is recommended to use eidors_cache with a function_handle.
   example:
        J = eidors_cache(@calc_jacobian_adjoint,img,'jacobian');
 See also: EIDORS_CACHE
CROSS-REFERENCE INFORMATION
This function calls:
eidors_msg EIDORS_MSG eidors progress and status messages
eidors_obj EIDORS_OBJ: maintains EIDORS internals
eidors_cache EIDORS_CACHE Control eidors caching
eidors_debug EIDORS_DEBUG Global managment of debug flags
unit_test_cmp UNIT_TEST_CMP: compare matrices in eidors output
This function is called by:
left_divide [V] = LEFT_DIVIDE(E,I,tol,pp,V);
ab_tv_diff_solve AB_TV_DIFF_SOLVE inverse solver for Andrea Borsic's
edge_refined_elem_mapper EDGE_REFINED_ELEM_MAPPER: map elements from coarse to dense model
edge_refined_node_mapper EDGE_REFINED_NODE_MAPPER:
fem_master_full function [E,D,Ela,pp] = fem_master_full(vtx,simp,mat,gnd_ind,elec,zc,perm_sym);
forward_solver [V] = forward_solver(E,I,tol,pp,V);
image_levels IMAGE_LEVELS(img, levels, clim) show slices at levels of an image
inv_solve_dual_mesh INV_SOLVE_DUAL_MESH using a coarse and fine mesh
m_3d_fields function [v_f] = m_3d_fields(vtx,el_no,m_ind,E,tol,gnd_ind,v_f);
manchester_tomography Example to show reconstructions from
np_calc_3d_fields NP_CALC_3D_FIELDS: J= np_calc_3d_fields(fwd_model, img)
np_calc_image_prior NP_CALC_IMAGE_PRIOR calculate image prior
np_calc_system_mat NP_CALC_SYSTEM_MAT: s_mat= np_calc_system_mat(fwd_model, img)
np_fwd_parameters NP_FWD_PARAMETERS: data= np_fwd_solve(fwd_model)
np_inv_solve NP_INV_SOLVE inverse solver for Nick Polydorides EIDORS3D code
set_fwd_model SET_FWD_MODEL: create EIDORS v3 fwd_model from v2 parameters
eidors_msg EIDORS_MSG eidors progress and status messages
eidors_obj EIDORS_OBJ: maintains EIDORS internals
eidors_startup Script to start EIDORS
cheating_2d code to simulate inverse crimes in EIT
compare_2d_algs Compare different 2D reconstructions
compare_3d_algs Compare different 3D reconstructions
demo_2d_simdata Example of using EIDORS to simulate 2D data and to
demo_3d_simdata How to make simulation data using EIDORS3D
demo_complex This demo function shows how the EIT problem can be formulated in a complex
demo_real [inhomg_img, demo_img] = demo_real;
resistor_model DEMO to show really simple application of EIDORS framework
calc_colours [colours,scl_data]= calc_colours(img, set_value, do_colourbar)
mdl_slice_mapper MDL_SLICE_MAPPER: map pixels to FEM elements or nodes
num_lights NUM_LIGHTS return the number of light objects in an axes
show_fem_enhanced SHOW_FEM_ENHANCED: show the EIDORS3D finite element model
calc_mesh_quality CALC_MESH_QUALITY Various measures of mesh quality.
dm_2d_pt_elecs DM_2D_PT_ELECS: Create circle mesh (or radius 1) refined
dm_mk_fwd_model DM_MK_FWD_MODEL: create a fwd_model object using distmesh
call_gmsh call_gmsh: call Gmsh to create a vol_file from a geo_file
create_circle_mesh_gmsh Create a 2D Circular FEM using GMSH
gmsh_mk_2d_model GMSH_MK_2D_MODEL create a 2D mesh with GMSH
gmsh_mk_fwd_model GMSH_MK_FWD_MODEL: create a fwd_model object from a Gmsh file
gmsh_stl2tet GMSH_STL2TET creates a tetrahedral mesh from an stl file
join_models JOIN_MODELS: Join two fmdl structures to create one
mat_idx_to_electrode MAT_IDX_TO_ELECTRODE: create electrodes from mat_idx values
mdl2d_from3d mdl2d_from3d: Create 2D mdl from z=0 plane of 3d model
ng_mk_2d_model NG_MG_2D_MODELS create a 2D mesh with Netgen via the in2d interface
ng_mk_cyl_models NG_MAKE_CYL_MODELS: create cylindrical models using netgen
ng_mk_ellip_models NG_MAKE_ELLIP_MODELS: create elliptical models using netgen
ng_mk_fwd_model NG_MK_FWD_MODEL: create a fwd_model object from a netgen vol file
ng_mk_gen_models NG_MK_GEN_MODELS: create generic models using netgen
ng_mk_geometric_models NG_MK_GEOMETRIC_MODELS: create geometric mesh models using Netgen. Body
ng_stl2tet NG_STL2TET creates a tetrahedral mesh from an stl file
stl_read STL_READ Read in an stl file and output an EIDORS model struct
add_noise ADD_NOISE: Add a given SNR to EIDORS data
convert_img_units CONVERT_IMG_UNITS change image data units
create_inclusion USAGE: inhomg_img = create_inclusion(homg_img, inclusion_xyz, ...
data_mapper DATA_MAPPER maps img.params data to elem or node data
fix_boundary FIX_BOUNDARY Orient boundary triangles consistently
fix_model FIX_MODEL: Add useful fields to a model
fwd_model_from_v2 CREATE EIDORS v3 fwd_model from the v2 variables
mdl_normalize MDL_NORMALIZE Check or set the normalize_measurements flag on a model.
merge_meshes MERGE_MESHES - merges two meshes sharing only boundary nodes
mk_GN_model MK_GN_MODEL: make EIDORS inverse models using the GREIT approach
mk_GREIT_model MK_GREIT_MODEL: make EIDORS inverse models using the GREIT approach
mk_c2f_circ_mapping MK_C2F_CIRC_MAPPING: create a mapping matrix from circles/spheres to FEM
mk_circ_tank MK_CIRC_TANK: make a cylindrical tank FEM geometry in 2D or 3D
mk_common_gridmdl MK_COMMON_MODEL: make EIT on reconstruction grids (GREIT)
mk_common_model MK_COMMON_MODEL: make common EIT models
mk_fmdl_from_nodes MK_FMDL_FROM_NODES: create fmdl from nodes
mk_geophysics_model imdl = mk_geophysics_model(str, ne, [option])
mk_grid_model MK_GRID_MODEL: Create reconstruction model on pixelated grid
mk_head_model_adult MK_HEAD_MODEL_ADULT Adult head model
mk_hollow_electrode MK_HOLLOW_ELECTRODE: remove nodes with indicated electrdoes
mk_image MK_IMAGE: create eidors image object
mk_library_model MK_LIBRARY_MODEL - extruded FEM models based on curves in SHAPE_LIBRARY
mk_pixel_slice MK_PIXEL_SLICE create a pixel model to reconstruct on
mk_thorax_model_bp3d MK_THORAX_MODEL_BP3D Torso model based on BodyParts3D
place_elec_on_surf PLACE_ELEC_ON_SURF Place electrodes on the surface of a model
point_in_tet POINT_IN_TET test for points contained in elements
set_predef_stim SET_PREDEF_STIM
select_imdl SELECT_IMDL: select pre-packaged inverse model features
simulate_2d_movement SIMULATE_2D_MOVEMENT simulate rotational movement in 2D
simulate_3d_movement SIMULATE_3D_MOVEMENT simulate rotational movement in 3D
write_hdf5_sample Write HDF5 Sample data
calc_jacobian CALC_JACOBIAN: calculate jacobian from an inv_model
calc_jacobian_bkgnd CALC_JACOBIAN_BKGND: calculate background image around
calc_meas_icov meas_icov = calc_meas_icov(inv_model)
fwd_solve_1st_order FWD_SOLVE_1ST_ORDER: data= fwd_solve_1st_order(img)
system_mat_instrument SYSTEM_MAT_INSTRUMENT:
update_system_mat_fields UPDATE_SYSTEM_MAT_FIELDS: fields (elem to nodes) fraction of system mat
fwd_solve FWD_SOLVE: calculate data from a fwd_model object and an image
inv_solve INV_SOLVE: calculate imag from an inv_model and data
GREIT_desired_img_FEMmesh GREIT_DESIRED_IMG_FEMmesh GREIT onto a FEM mesh
calc_noise_figure CALC_NOISE_FIGURE: calculate the noise amplification (NF) of an algorithm
inv_solve_TV_pdipm INV_SOLVE_TV_PDIPM inverse solver for Andrea Borsic's
inv_solve_abs_annealingMetropolis_params INV_SOLVE_ABS_ANNEALINGSIMPLEX_PARAMS absolute solver using the simplex annealing method.
inv_solve_abs_annealingSimplex_params INV_SOLVE_ABS_ANNEALINGSIMPLEX_PARAMS absolute solver using the simplex annealing method.
inv_solve_backproj INV_SOLVE_BACKPROJ inverse solver using backprojection
primaldual_tvrecon_lsearch [rs,x]=primaldual_tvrecon_lsearch(inv_mdl, vmeas, ...
cache_limit_test Test cache deletes in the right order
calc_data_prior_test Verify dataprior:
demo_real_test2 Perform tests based on the demo_real function with new structs
demo_real_test3 Perform tests based on the demo_real function with new structs
test_2d_resistor Create 2D model of a cylindrical resistor
test_3d_resistor Create 3D model of a Rectangular resistor
test_c2f_jacobian Test calc of jacobian given coarse to fine mapping
test_colour_direction Test colour mapping
eidors_cache EIDORS_CACHE Control eidors caching
subtract_rank SUBTRACK_RANK: subtract a ranked level from data
test_performance TEST_PERFORMANCE: test of difference reconstruction algorithms
test_performance_img TEST_PERFORMANCE: test of difference reconstruction algorithms
SUBFUNCTIONS
function ok = status_check(name)
function on = debug_status_check
function out = cache_status(fname)
function out = debug_status(fname)
function test_install
function verstr = test_versions;
function obj = set_obj(obj, varargin);
function obj = order_fields(obj)
function [value, obj_id] = get_cache_obj(obj, prop)
function obj_id = set_cache_obj(obj, prop, value, time)
function cache_init
function score = calc_size_score(sz)
function score = calc_effort_score(time, counts, prios)
function obj= new_obj(type, name, varargin);
function obj_id= calc_obj_id(var)
function test_for_cachdir
function [objlist, cachedir]= proc_obj_list(varargin);
function retval= cache_this(obj)
function check_size(obj_id , prop)
function do_unit_test
SOURCE CODE
function [obj_id, extra_out] = eidors_obj(type,name, varargin)
% EIDORS_OBJ: maintains EIDORS internals
%
% USAGE: to get eidors_version
%     version = eidors_obj('eidors_version')
%
% USAGE: to get interpreter version:
%     version = eidors_obj('interpreter_version')
%
% USAGE: to get path to EIDORS:
%     path = eidors_obj('eidors_path');
%
% USAGE: (for developers) to create a new eidors object:
%     obj = eidors_obj('fwd_model','obj name','nodes',N,'elems',E,...)
%     obj = eidors_obj('fwd_model',mdl_struct,'name','obj name',..)
%     obj = eidors_obj('fwd_model',mdl_struct);
% will return an object of type 'fwd_model' with standardized field order.
%
% USAGE: (for developers) to set fields on existing objects:
%     obj = eidors_obj('set',obj,'name','obj name',...);
%     obj = eidors_obj('set',obj);
% will return an object with standardized field order.
%
% USAGE: to cache values (not recommended)
%            obj_id = eidors_obj('set-cache',obj, cachename,value, [time])
%     [obj, obj_id] = eidors_obj('get-cache',obj, cachename)
%
% this will get or set the values of cached properties of the object.
%
%    example: % set jacobian
%        obj_id = eidors_obj('set-cache',cache_obj, 'jacobian', J);
%
%    example: % get jacobian or '[]' if not set
%        [J, obj_id] = eidors_obj('get-cache',cache_obj, 'jacobian');
%
% It is recommended to combine in cache_obj the minimum set of variables on
% which the value to be cached depends.
%    example: % cache_obj for jacobian
%        cache_obj = {img.fwd_model.nodes, img.fwd_model.elems ...
%                     img.elem_data, img.fwd_model.jacobian}
%
% NOTE that rather than directly using eidors_obj to set and get cache, it
% is recommended to use eidors_cache with a function_handle.
%
%   example:
%        J = eidors_cache(@calc_jacobian_adjoint,img,'jacobian');
%
% See also: EIDORS_CACHE
% (C) 2005-10 Andy Adler. License: GPL version 2 or version 3
% $Id: eidors_obj.m 7121 2024-12-29 14:45:56Z aadler $
if isstruct(type)
   if isfield(type,'type');
      obj_id = type.type;
   else
      obj_id = '{non-eidors}';
   end
   return
end
if ~ischar(type); % type of a non-eidors char
   obj_id = []; %
   return
end
if nargin==0
   error('cannot call eidors_obj with no arguments');
end
switch type
   case 'UNIT_TEST';
      do_unit_test; return
% Return the type of an eidors object
   case 'set'
      obj_id= set_obj( name, varargin{:} );
   case 'get-cache'
      test_install
      obj_id = []; extra_out= [];
      if status_check(varargin{1})
        [obj_id, extra_out] = get_cache_obj( name, varargin{:} );
      end
   case 'set-cache'
      test_install
      obj_id= [];
      if status_check(varargin{1})
          obj_id = set_cache_obj( name, varargin{:} );
      end
   case 'eidors_version'
      obj_id= '3.12';  % Update for New eidors version
   case 'eidors_path'
      global eidors_objects
      obj_id = eidors_objects.eidors_path;
   case 'interpreter_version'
      obj_id= test_versions;
% TODO: Add these functions
%  case 'eidors_path'
%  case 'eidors_dev_path'
%  case 'eidors_cache_path'
   case 'cache_init'
      cache_init;
   otherwise
      test_install
      obj_id= new_obj( type, name, varargin{:} );
end
function ok = status_check(name)
ok = true;
switch cache_status
    case 0
        ok = false;
    case 0.5
        dbs = dbstack;
        if cache_status(dbs(3).name) == 0
            ok = false;
        end
        if strcmp(dbs(3).name,'cache_shorthand') && cache_status(dbs(5).name) == 0
            ok = false;
        end
        if cache_status(name) == 0
           ok = false;
        end
end
function on = debug_status_check
on = false;
switch debug_status
    case 1
        on = true;
    case 0.5
        dbs = dbstack;
        if debug_status(dbs(3).name) == 1
            on = true;
        end
end
function out = cache_status(fname)
    global eidors_objects;
    if nargin == 0
        try
            out = eidors_objects.cache_enable;
        catch
            out = 1;
        end
    else
        out = ~any(strcmp(eidors_objects.cache_disabled_on,fname));
    end
function out = debug_status(fname)
   global eidors_objects;
   if nargin == 0
      try
         out = eidors_objects.debug_enable;
      catch
         out = 0;
      end
   else
      out = ~any(strcmp(eidors_objects.debug_enabled_on,fname));
   end
function test_install
  global eidors_objects;
  if isfield(eidors_objects,'max_cache_size'); return; end % OK
  error('EIDORS not correctly started. Did you do ">>run /path/to/eidors/startup"');
function verstr = test_versions;
      ver= version; ver(ver=='.')=' ';
      ver = sscanf(ver,'%f'); ver=ver(:);
      % build numbers are too large and interfere
      ver(4:end) = [];
      % Convert 7.8.1 to 7.008001
      verstr.ver = 1e-3.^(0:length(ver)-1) * ver(:);
      if exist('OCTAVE_VERSION') == 5
         verstr.isoctave = 1;
      else
         verstr.isoctave = 0;
      end
      cptr = computer;
      if strcmp(cptr(end+(-1:0)), '64')
         verstr.is64bit = 1;
      else
         verstr.is64bit = 0;
      end
function obj = set_obj(obj, varargin);
   for idx= 1:2:nargin-1
      obj.( varargin{idx} )= varargin{idx+1};
   end
   obj = order_fields(obj);
function obj = order_fields(obj)
   if ~isfield(obj, 'type'), return, end
   switch obj.type
      case 'fwd_model'
         field_order = {'type', 'name',...
            'nodes', 'elems', 'boundary', ...
            'electrode', ...
            'stimulation', 'meas_select', ...
            'solve', 'jacobian', 'system_mat', ...
            'normalize_measurements', 'gnd_node', ...
            'boundary_numbers','mat_idx', 'mat_names'};
      case 'inv_model'
         field_order = {'type', 'name',...
            'fwd_model', 'rec_model','jacobian_bkgnd' ...
            'reconst_type','solve', ...
            'hyperparameter'};
      case 'rec_model'
         field_order = {'type', 'name',...
            'nodes', 'elems'};
      case 'image'
         field_order = {'type', 'name', 'fwd_model', ...
            'elem_data', 'node_data'};
      case 'data'
         field_order = {'type', 'name', 'meas'};
      otherwise
         warning(['Encountered an unexpected object type: ', obj.type,  ...
            'Please report on the eidors mailing list if it''s not your typo.'])
         return
   end
   fnames = fieldnames(obj);
   [~,known_idx] = ismember(fnames,field_order);
   field_idx = find(known_idx);
   known_order = sortrows([nonzeros(known_idx), field_idx]);
   [~, unknown_order] = sort(fnames(known_idx==0));
   perm = zeros(numel(fnames),1);
   perm(1:numel(field_idx)) = known_order(:,2);
   perm(numel(field_idx) + unknown_order) = find(known_idx==0);
   obj = orderfields(obj,perm);
   try obj.fwd_model = order_fields(obj.fwd_model); end
   try obj.rec_model = order_fields(obj.rec_model); end
% val= get_cache_obj(obj, prop, dep_obj1, dep_obj2, ...,  cachename);
function [value, obj_id] = get_cache_obj(obj, prop)
   global eidors_objects
   DEBUG = eidors_debug('query','eidors_obj');
   value= [];
   obj_id = [];
   if DEBUG, str = sprintf('cache request: %s ',prop); end
% We don't do this since cache directories aren't defined (yet)
%  [objlist, cachename]= proc_obj_list(varargin{:});
   if ~isfield(eidors_objects, 'cache')
      cache_init;
      if DEBUG, fprintf('%s: NO CACHE FIELD\n',str); end
      return
   end
   obj_id= calc_obj_id( { obj, prop} );
   if isempty(eidors_objects.cache.meta),
      if DEBUG, fprintf('%s: NO META FIELD\n',str); end
      return
   end
   c = eidors_objects.cache.cols;
%    match = ismember(prop, eidors_objects.cache.meta(:,c.prop));
%    if any(match)
   if DEBUG, str = [str, obj_id]; end
% if cachename is specified, then cache to that file, rather
%  than to the standard eidors_objects location
% TODO: fixthis - use () for matlab > 6.0
%  if ~isempty(cachename)
%     test_for_cachdir;
%     filename= [ eidors_objects.cachedir, '/' , prop, '_' cachename '.mat' ];
%     if exist(filename, 'file')
%        load(filename); %variable 'value' should be there
%     end
%  else
      if ~isfield( eidors_objects.cache, obj_id);
         if DEBUG, fprintf('%s: not found\n',str); end
         return
      end
      idx = find(strcmp(obj_id, eidors_objects.cache.meta(:,c.obj_id)), 1, 'first');
      if DEBUG && isempty(idx), fprintf('%s: EMPTY IDX !!\n',str); end
      if ~isempty(idx)
         eidors_objects.cache.meta{idx,c.time} = now;
         eidors_objects.cache.meta{idx,c.count} = eidors_objects.cache.meta{idx,c.count} + 1;
         eidors_objects.cache.meta{idx,c.score_eff} = calc_effort_score(...
            eidors_objects.cache.meta{idx,c.effort}, ...
            eidors_objects.cache.meta{idx,c.count}, ...
            eidors_objects.cache.meta{idx,c.prio});
      end
      value = eidors_objects.cache.(obj_id);
      if DEBUG, fprintf('%s: found\n',str); end
%        value= eval(sprintf('eidors_objects.%s.cache.%s;',obj_id,prop));
%          check_size(obj_id, prop);
%  end
%    end
function obj_id = set_cache_obj(obj, prop, value, time)
   global eidors_objects
   obj_id = [];
   if ~cache_this( obj ) ; return ; end
   if nargin  < 4
      time = 1; % assume 1 sec
   end
   if ~isfield(eidors_objects,'cache');
      init_cache;
   end
   c = eidors_objects.cache.cols;
% Cache directories aren't defined, yet
%  [objlist, cachename]= proc_obj_list(varargin{:});
   obj_id = calc_obj_id( {obj, prop} );
   prio = eidors_objects.cache_priority;
%  if isempty(cachename)
      ws = whos('value');
      row(c.obj_id)   = {obj_id};
      row(c.prop)     = {prop};
      row(c.size)     = {ws.bytes};
      row(c.score_sz) = {calc_size_score(ws.bytes)};
      row(c.effort)   = {time};
      row(c.prio)     = {prio};
      row(c.count)    = {1};
      row(c.score_eff)= {calc_effort_score(time, 1, prio)};
      row(c.time)     = {now};
      if isfield(eidors_objects.cache, obj_id)
         idx = find(strcmp(obj_id, eidors_objects.cache.meta(:,c.obj_id)));
         eidors_msg('@@ replaced cache object %s { %s }', obj_id, prop,4);
         eidors_objects.cache.size = eidors_objects.cache.size ...
                                    - eidors_objects.cache.meta{idx,c.size};
      else
         idx = size(eidors_objects.cache.meta, 1) + 1;
      end
      eidors_objects.cache.meta(idx,:) = row;
      eidors_objects.cache.( obj_id ) = value;
      eidors_objects.cache.size = eidors_objects.cache.size + ws.bytes;
      check_size(obj_id, prop);
%  else
%     filename= [ eidors_objects.cachedir, '/' , prop, '_' cachename '.mat' ];
%     save(filename, 'value');
%  end
function cache_init
   global eidors_objects;
   eidors_objects.cache = struct;
   eidors_objects.cache.meta = cell(0);
   eidors_objects.cache.cols.obj_id    = 1;
   eidors_objects.cache.cols.prop      = 2;
   eidors_objects.cache.cols.time      = 3;
   eidors_objects.cache.cols.size      = 4;
   eidors_objects.cache.cols.score_sz  = 5;
   eidors_objects.cache.cols.effort    = 6;
   eidors_objects.cache.cols.prio      = 7;
   eidors_objects.cache.cols.count     = 8;
   eidors_objects.cache.cols.score_eff = 9;
   eidors_objects.cache.size           = 0;
function score = calc_size_score(sz)
   if iscell(sz)
      fn = @(b) round(10*log10(b / 1024));
      N = numel(sz);
      score = num2cell(cellfun(fn, sz));
   else
      score = round(10 * log10( sz / 1024));
   end
function score = calc_effort_score(time, counts, prios)
   if iscell(time)
       score = num2cell( round(10*log10( cell2mat(time) .* cell2mat(counts))) +...
                                cell2mat(prios));
   else
      score = round(10*log10(time .* counts)) + prios;
   end
function obj= new_obj(type, name, varargin);
   if isstruct(name)
      obj= name;
      try
         name= obj.name;
      catch
         name= 'unknown';
      end
   end
   obj.type = type;
   obj.name = name;
   obj= set_obj(obj, varargin{:} );
% This function hashes the value of the variable var
% to create an obj_id. The goal is to allow proper caching
% of calculated matrices, by detecting when a previous
% calculation with same parameters has been made
function obj_id= calc_obj_id(var)
   try
      obj_id= eidors_var_id( var );
   catch
      global eidors_objects;
      if ~isfield(eidors_objects,'hash_type')
         eidors_objects.hash_type= 1e8+1;
      end
%if hashing code is unavailable, then disable caching function
      obj_id= sprintf('id_%031d%08d', 0,eidors_objects.hash_type );
      eidors_objects.hash_type= eidors_objects.hash_type + 1;
   end
% Test whether the cachedir field has been set. This is
%  where eidors will store cached calculations. If it has
%  not been set, then create it as 'eidors_cache' in the
%  current directory
%
% NOTE: This code is not (yet) used
function test_for_cachdir
   global eidors_objects;
   if ~isfield(eidors_objects, 'cachedir')
      cachedir= 'eidors_cache';
      eidors_objects.cachedir= [pwd,'/',cachedir];
      if ~exist( eidors_objects.cachedir, 'dir')
% Now we need to ensure that cachedir exists. Because the
% STUPID!!! matlab has a completely useless and nonstandard
% mkdir function, we try this
         mkdir(pwd,cachedir);
      end
   end
% Test whether a cachedir function has been provided
% (by testing whether the last entry is a string). If so,
% return it in objlist, otherwise return []
function [objlist, cachedir]= proc_obj_list(varargin);
   cachedir= [];
   if nargin==0
      objlist= {};
   elseif ischar(varargin{nargin})
      cachedir= varargin{nargin};
      objlist = varargin(1:nargin-1);
   else
      objlist = varargin(:);
   end
function retval= cache_this(obj)
% we choose not to cache data and images because this will
% tend to fill up the workspace.
% TODO: make the DONT_CACHE list use configuable
   if ~isstruct( obj); retval=1; return; end
   DONT_CACHE= {'data','image'};
   if any(strcmp( obj.type, DONT_CACHE));
      retval = 0;
   else
      retval = 1;
   end
function check_size(obj_id , prop)
   global eidors_objects;
%    eidors_objects.(obj_id).(prop).last_used = now;
   max_memory= eidors_objects.max_cache_size;
%    ww= whos('eidors_objects');
   if eidors_objects.cache.size  > max_memory
      eidors_cache('clear_max',floor(max_memory*.75));
   end
% TODO: Lots to write here
function do_unit_test
   im = eidors_obj('image','','elem_data',1);
   et = eidors_obj(im);
   unit_test_cmp('type 0',et,'image');