Description of jacobian_perturb
Home > eidors > solvers > forward > jacobian_perturb.m
jacobian_perturb
PURPOSE
JACOBIAN_PERTURB: J= jacobian_perturb(fwd_model, img)
SYNOPSIS
function J= jacobian_perturb(fwd_model, img)
DESCRIPTION
 JACOBIAN_PERTURB: J= jacobian_perturb( fwd_model, img)
 Calculate Jacobian Matrix, based on small perturbations
   in the forward model. This will tend to be slow, but
   should be best used to 'sanity check' other code
 J         = Jacobian matrix
 fwd_model = forward model
 fwd_model.jacobian_perturb.delta   - delta perturbation to use (default 1e-6)
 img = image background for jacobian calc
CROSS-REFERENCE INFORMATION
This function calls:
data_mapper DATA_MAPPER maps img.params data to elem or node data
mdl_normalize MDL_NORMALIZE Check or set the normalize_measurements flag on a model.
mk_common_model MK_COMMON_MODEL: make common EIT models
calc_jacobian CALC_JACOBIAN: calculate jacobian from an inv_model
calc_jacobian_bkgnd CALC_JACOBIAN_BKGND: calculate background image around
fwd_solve_1st_order FWD_SOLVE_1ST_ORDER: data= fwd_solve_1st_order(img)
jacobian_adjoint JACOBIAN_ADJOINT: J= jacobian_adjoint(img)
jacobian_perturb JACOBIAN_PERTURB: J= jacobian_perturb(fwd_model, img)
system_mat_1st_order SYSTEM_MAT_1ST_ORDER: SS= system_mat_1st_order(fwd_model, img)
fwd_solve FWD_SOLVE: calculate data from a fwd_model object and an image
unit_test_cmp UNIT_TEST_CMP: compare matrices in eidors output
This function is called by:
perturb_jacobian PERTURB_JACOBIAN: J= perturb_jacobian(fwd_model, img)
jacobian_movement_halfspace JACOBIAN_MOVEMENT_PERTURB: J= jacobian_movement_perturb(img)
jacobian_movement_perturb JACOBIAN_MOVEMENT_PERTURB: J= jacobian_movement_perturb(img)
jacobian_perturb JACOBIAN_PERTURB: J= jacobian_perturb(fwd_model, img)
test_2d_resistor Create 2D model of a cylindrical resistor
test_3d_resistor Create 3D model of a Rectangular resistor
test_c2f_jacobian Test calc of jacobian given coarse to fine mapping
SUBFUNCTIONS
function Jcol= perturb(img, i, delta, d0, curprms)
function Jcol= perturb_c2f(img, i, delta, d0, curprms)
function do_unit_test
function display_jacobian_deltas(img, J);
SOURCE CODE
function J= jacobian_perturb(fwd_model, img)
% JACOBIAN_PERTURB: J= jacobian_perturb(fwd_model, img)
% Calculate Jacobian Matrix, based on small perturbations
%   in the forward model. This will tend to be slow, but
%   should be best used to 'sanity check' other code
%
% J         = Jacobian matrix
% fwd_model = forward model
% fwd_model.jacobian_perturb.delta   - delta perturbation to use (default 1e-6)
% img = image background for jacobian calc
% (C) 2006 Andy Adler. License: GPL version 2 or version 3
% $Id: jacobian_perturb.m 6721 2024-04-02 18:37:40Z aadler $
if ischar(fwd_model) && strcmp(fwd_model,'UNIT_TEST'); do_unit_test; return;end
if isfield(fwd_model,'jacobian_perturb')
   delta = fwd_model.jacobian_perturb.delta;
else
   delta= 1e-6; % tests indicate this is a good value
end
n_elem = size(fwd_model.elems,1);
% force image to use provided fwd_model
img.fwd_model= fwd_model;
jnk = data_mapper(img);
curprms = jnk.current_params;
if strcmp(curprms, 'conductivity') && ~isfield(img,'conductivity')
   curprms = '';
end
% solve one time to get the size
d0= fwd_solve(img);
if isfield(img.fwd_model,'coarse2fine');
   Jcol= perturb_c2f(img, 1, delta, d0, curprms);
   Jrows= size(img.fwd_model.coarse2fine,2);
   J= zeros(length(Jcol), Jrows );
   J(:,1)= Jcol;
   for i=2:size(img.fwd_model.coarse2fine,2);
     J(:,i)= perturb_c2f(img, i, delta, d0, curprms);
     if rem(i,50)==0; fprintf('+'); end
   end
else
   Jcol= perturb(img, 1, delta, d0, curprms);
   J= zeros(length(Jcol), n_elem);
   J(:,1)= Jcol;
   for i=2:n_elem
     J(:,i)= perturb(img, i, delta, d0, curprms);
   end
end
function Jcol= perturb(img, i, delta, d0, curprms)
   if ~isempty(curprms)
      img.(curprms).elem_data(i)= img.(curprms).elem_data(i) + delta;
   else
      img.elem_data(i)= img.elem_data(i) + delta;
   end
   di= fwd_solve( img );
   Jcol = (1/delta) * (di.meas - d0.meas);
function Jcol= perturb_c2f(img, i, delta, d0, curprms)
   if ~isempty(curprms)
      img.(curprms).elem_data= img.(curprms).elem_data + delta*img.fwd_model.coarse2fine(:,i);
   else
       img.elem_data(i)= img.elem_data(i) + delta; %*img.fwd_model.coarse2fine(:,i);
%       img.elem_data= img.fwd_model.coarse2fine*img.elem_data + delta*img.fwd_model.coarse2fine(:,i);
   end
   di= fwd_solve( img );
   Jcol = (1/delta) * (di.meas - d0.meas);
function do_unit_test
% Perturbation Jacobians
% $Id: jacobian_perturb.m 6721 2024-04-02 18:37:40Z aadler $
  models ={'c2c2','a3cr','n3r2'};
  for delta = [1e-7,1e-6,1e-5,1e-4];
     fprintf('Using delta = %6.3g\n',delta);
  for i = 1:length(models);
     Nel = 16; if i==3; Nel=[16,2]; end
     imdl= mk_common_model(models{i},Nel);
     imdl.fwd_model.nodes = imdl.fwd_model.nodes*.25;
     img= calc_jacobian_bkgnd(imdl);
     img.fwd_model = mdl_normalize(img.fwd_model, 0);
     img.fwd_model.jacobian=   @jacobian_adjoint;
     img.fwd_model.system_mat= @system_mat_1st_order;
     img.fwd_model.solve=      @fwd_solve_1st_order;
     J_aa= calc_jacobian( img );
%    display_jacobian_deltas(img, J_aa) % show perturbation size
     img.fwd_model.jacobian=   @jacobian_perturb;
     img.fwd_model.jacobian_perturb.delta = delta;
     J_aa_p= calc_jacobian( img );
     unit_test_cmp(['J_ - J_p:', img.fwd_model.name] , J_aa, J_aa_p, 1e-4);
   end
   end
function display_jacobian_deltas(img, J);
% Calculate the perturbation Jacobian
  vh= fwd_solve(img);
  for el= 1:50:size(img.fwd_model.elems,1);
     fprintf('\nelem#%03d: ',el);
     for delta= [1e-4,1e-6,1e-8] % delta is perturb
        img_i = img;
        img_i.elem_data(el)= img_i.elem_data(el) + delta;
        vi= fwd_solve(img_i);
        J_p = (vi.meas - vh.meas)/delta; % perturb Jacobian
        fprintf(' %8.6f', norm(J_p - J(:,el))/norm(J(:,el)));
     end
  end