Description of fix_boundary
Home > eidors > models > fix_boundary.m
fix_boundary
PURPOSE
FIX_BOUNDARY Orient boundary triangles consistently
SYNOPSIS
function mdl = fix_boundary(mdl)
DESCRIPTION
FIX_BOUNDARY Orient boundary triangles consistently
 mdl = FIX_BOUNDARY(mdl) changes or adds mdl.boundary to an eidors
  fwd_model
 See also FIX_MODEL
CROSS-REFERENCE INFORMATION
This function calls:
eidors_obj EIDORS_OBJ: maintains EIDORS internals
fix_model FIX_MODEL: Add useful fields to a model
This function is called by:
ng_stl2tet NG_STL2TET creates a tetrahedral mesh from an stl file
mk_head_model MK_HEAD_MODEL FEM models of the head
mk_head_model_adult MK_HEAD_MODEL_ADULT Adult head model
mk_thorax_model MK_THORAX_MODEL FEM models of the thorax
mk_thorax_model_bp3d MK_THORAX_MODEL_BP3D Torso model based on BodyParts3D
place_elec_on_surf PLACE_ELEC_ON_SURF Place electrodes on the surface of a model
SOURCE CODE
function mdl = fix_boundary(mdl)
%FIX_BOUNDARY Orient boundary triangles consistently
% mdl = FIX_BOUNDARY(mdl) changes or adds mdl.boundary to an eidors
%  fwd_model
%
% See also FIX_MODEL
% (C) 2015-2016 Bartlomiej Grychtol. License: GPL version 2 or 3
% $Id: fix_boundary.m 6926 2024-05-31 15:34:13Z bgrychtol $
opt.elem2face  = 1;
opt.boundary_face = 1;
opt.inner_normal = 1;
tmp = fix_model(mdl,opt);
flip = tmp.elem2face(logical(tmp.boundary_face(tmp.elem2face).*tmp.inner_normal));
tmp.faces(flip,:) = tmp.faces(flip,[1 3 2]);
tmp.normals(flip,:) = -tmp.normals(flip,:);
% don't pollute the model, but make existing relevant fields consistent
fields = {'faces', 'normals', 'inner_normal', 'boundary_face'};
for i = 1:numel(fields)
   if isfield(mdl, fields{i})
      mdl.(fields{i}) = tmp.(fields{i});
   end
end
mdl.boundary = tmp.faces(tmp.boundary_face,:);
mdl = eidors_obj('set', mdl);