Description of mdl_normalize
Home > eidors > models > mdl_normalize.m
mdl_normalize
PURPOSE
MDL_NORMALIZE Check or set the normalize_measurements flag on a model.
SYNOPSIS
function out = mdl_normalize(mdl, val)
DESCRIPTION
MDL_NORMALIZE Check or set the normalize_measurements flag on a model.
  OUT = MDL_NORMALIZE(MDL) returns the value of the
  'normalize_measurements' or 'normalize' field on MDL. If absent, the
  default value is returned as set with EIDORS_DEFAULT.
  MDL = MDL_NORMALIZE(MDL, VAL) sets the 'normalize_measurements' to VAL
  MDL = MDL_NORMALIZE(MDL, 'default') uses the EIDORS_DEFAULT value to set
  set the 'normalize_measurements' flag on the model.
  OUT = MDL_NORMALIZE('default') returns the EIDORS_DEFAULT value to set
  set the 'normalize_measurements' flag on the model.
 See also: FWD_MODEL_PARAMETERS, EIDORS_DEFAULT, EIDORS_STARTUP
CROSS-REFERENCE INFORMATION
This function calls:
eidors_msg EIDORS_MSG eidors progress and status messages
eidors_obj EIDORS_OBJ: maintains EIDORS internals
mdl_normalize MDL_NORMALIZE Check or set the normalize_measurements flag on a model.
mk_common_model MK_COMMON_MODEL: make common EIT models
eidors_default EIDORS_DEFAULT Default function handler.
unit_test_cmp UNIT_TEST_CMP: compare matrices in eidors output
This function is called by:
calc_noise_params params = GREIT_noise_params(imdl, homg_voltage, sig_voltage)
eidors_model_params mdl = eidors_model_params(mdl);
compare_2d_algs Compare different 2D reconstructions
fwd_model_device FMDL_MODEL_DEVICE: set vendor/device specific parameters
dm_mk_fwd_model DM_MK_FWD_MODEL: create a fwd_model object using distmesh
gmsh_mk_fwd_model GMSH_MK_FWD_MODEL: create a fwd_model object from a Gmsh file
mdl2d_from3d mdl2d_from3d: Create 2D mdl from z=0 plane of 3d model
ng_mk_fwd_model NG_MK_FWD_MODEL: create a fwd_model object from a netgen vol file
ng_mk_geometric_models NG_MK_GEOMETRIC_MODELS: create geometric mesh models using Netgen. Body
mdl_normalize MDL_NORMALIZE Check or set the normalize_measurements flag on a model.
mk_GN_model MK_GN_MODEL: make EIDORS inverse models using the GREIT approach
mk_GREIT_model MK_GREIT_MODEL: make EIDORS inverse models using the GREIT approach
mk_circ_tank MK_CIRC_TANK: make a cylindrical tank FEM geometry in 2D or 3D
mk_common_gridmdl MK_COMMON_MODEL: make EIT on reconstruction grids (GREIT)
mk_common_model MK_COMMON_MODEL: make common EIT models
mk_fmdl_from_nodes MK_FMDL_FROM_NODES: create fmdl from nodes
mk_grid_model MK_GRID_MODEL: Create reconstruction model on pixelated grid
mk_head_model MK_HEAD_MODEL FEM models of the head
mk_library_model MK_LIBRARY_MODEL - extruded FEM models based on curves in SHAPE_LIBRARY
mk_thorax_model MK_THORAX_MODEL FEM models of the thorax
mk_thorax_model_grychtol2016a Builds the male thorax models from Grychtol, Müller and Adler (2016)
place_elec_on_surf PLACE_ELEC_ON_SURF Place electrodes on the surface of a model
simulate_2d_movement SIMULATE_2D_MOVEMENT simulate rotational movement in 2D
simulate_3d_movement SIMULATE_3D_MOVEMENT simulate rotational movement in 3D
simulate_movement SIMULATE_MOVEMENT simulate small conductivity perturbations
test_GREIT_model
calc_R_prior R = calc_R_prior(inv_model, varargin)
calc_RtR_prior RtR = calc_RtR_prior(inv_model)
calc_difference_data CALC_DIFFERENCE_DATA: calculate difference data between
calc_jacobian CALC_JACOBIAN: calculate jacobian from an inv_model
calc_meas_icov meas_icov = calc_meas_icov(inv_model)
fwd_model_parameters FWD_MODEL_PARAMETERS: data= fwd_solve_1st_order(fwd_model, image)
fwd_solve_1st_order FWD_SOLVE_1ST_ORDER: data= fwd_solve_1st_order(img)
jacobian_adjoint_higher_order Find the Jacobian associated with an image (and forward model)
jacobian_apparent_resistivity jacobian_apparent_resistivity: Jacobian output as apparent resistivity
jacobian_movement JACOBIAN_MOVEMENT Computes the Jacobian matrix for conductivity and
jacobian_movement_halfspace JACOBIAN_MOVEMENT_PERTURB: J= jacobian_movement_perturb(img)
jacobian_movement_perturb JACOBIAN_MOVEMENT_PERTURB: J= jacobian_movement_perturb(img)
jacobian_perturb JACOBIAN_PERTURB: J= jacobian_perturb(fwd_model, img)
system_mat_instrument SYSTEM_MAT_INSTRUMENT:
fwd_solve FWD_SOLVE: calculate data from a fwd_model object and an image
inv_solve INV_SOLVE: calculate imag from an inv_model and data
calc_noise_figure CALC_NOISE_FIGURE: calculate the noise amplification (NF) of an algorithm
test_3d_resistor Create 3D model of a Rectangular resistor
SUBFUNCTIONS
function out = get_flag(mdl)
function mdl = set_flag(mdl, val)
function do_unit_test
SOURCE CODE
function out = mdl_normalize(mdl, val)
%MDL_NORMALIZE Check or set the normalize_measurements flag on a model.
%  OUT = MDL_NORMALIZE(MDL) returns the value of the
%  'normalize_measurements' or 'normalize' field on MDL. If absent, the
%  default value is returned as set with EIDORS_DEFAULT.
%
%  MDL = MDL_NORMALIZE(MDL, VAL) sets the 'normalize_measurements' to VAL
%
%  MDL = MDL_NORMALIZE(MDL, 'default') uses the EIDORS_DEFAULT value to set
%  set the 'normalize_measurements' flag on the model.
%
%  OUT = MDL_NORMALIZE('default') returns the EIDORS_DEFAULT value to set
%  set the 'normalize_measurements' flag on the model.
%
% See also: FWD_MODEL_PARAMETERS, EIDORS_DEFAULT, EIDORS_STARTUP
% (C) 2012 Bartlomiej Grychtol. License: GPL v2 or v3
% $Id: mdl_normalize.m 7043 2024-11-30 14:46:20Z aadler $
if ischar(mdl) && strcmp(mdl, 'UNIT_TEST'); do_unit_test; return; end
if ischar(mdl) && strcmp(mdl, 'default')
   out = eidors_default;
   return
end
% check that we got a fwd_model
try
   switch mdl.type
      case 'fwd_model'
         % do nothing
      case 'image'
         img = mdl;
         mdl = img.fwd_model;
      otherwise
         error('EIDORS:WrongInput','Expected fwd_model or image.');
   end
catch
   warning('EIDORS:UnknownType','Object has no type. Assuming fwd_model.');
end
% do the real thing
switch nargin
    case 1
        out = get_flag(mdl);
        if isempty(out)
            out = eidors_default;
            warning('EIDORS:normalize_flag_not_set', ...
                'normalize_measurements flag not set on model. Using default: %d',out);
        end
    case 2
        if ischar(val) && strcmp(val, 'default')
           val = eidors_default;
        end
        out = set_flag(mdl,val);
        if exist('img','var') % input was an image
           img.fwd_model = out;
           out = img;
        end
    otherwise
        error('Wrong number of parameters');
end
function out = get_flag(mdl)
 out = [];
% iterate over fields
ff = fieldnames(mdl);
for i = 1:length(ff);
    % if both are set, you're in trouble
    if any(strcmp(ff{i},{'normalize','normalize_measurements'}))
        out = mdl.(ff{i});
    else
        % won't hit 'normal' or anything that starts with 'normals'.
        token = regexp(ff{i},'normal[^s]+.*','match','once');
        if ~isempty(token);
            warning('Suspect field "%s" found on the model',token);
        end
    end
end
function mdl = set_flag(mdl, val)
mdl = eidors_obj('set',mdl, 'normalize_measurements', val);
function do_unit_test
s = warning('query', 'backtrace');
warning off backtrace;
eidors_default('set','mdl_normalize',@(x) 0);
mdl = mk_common_model('c2t2',16);
fmdl = mdl.fwd_model;
unit_test_cmp('Does it come normalized?', mdl_normalize(fmdl), 0);
fmdl = mdl_normalize(fmdl,1);
unit_test_cmp('Normalize it. How about now?', mdl_normalize(fmdl), 1);
fmdl = mdl_normalize(fmdl,0);
unit_test_cmp('De-normalize it. And now?', mdl_normalize(fmdl), 0);
fmdl = rmfield(fmdl,'normalize_measurements');
eidors_msg(mdl_normalize(fmdl));
unit_test_cmp('Remove the flag', ...
   lastwarn, 'normalize_measurements flag not set on model. Using default: 0');
fmdl.normalise_measurements = 1; % s, throw a warning, return default
eidors_msg(mdl_normalize(fmdl));
unit_test_cmp('Spelling error', ...
   lastwarn, 'normalize_measurements flag not set on model. Using default: 0');
fmdl.normalize_my_gran = 1; % throw a warning, return default
eidors_msg(mdl_normalize(fmdl));
unit_test_cmp('And now let''s set it to something stupid', ...
   lastwarn, 'normalize_measurements flag not set on model. Using default: 0');
fmdl.normalize = 1; % accept happily
unit_test_cmp('Accept happily', mdl_normalize(fmdl), 1);
eidors_msg('But an imdl is not acceptable!');
try
    eidors_msg(mdl_normalize(mdl));
catch
    unit_test_cmp('Just so.', 1,1);
end
warning(s);