Description of remove_instrument_electrodes
Home > eidors > models > remove_instrument_electrodes.m
remove_instrument_electrodes
PURPOSE
pre-delete all 'instrument' nodes
SYNOPSIS
function fmdl = remove_instrument_electrodes(fmdl)
DESCRIPTION
 pre-delete all 'instrument' nodes
 system matrix can't handle them
 NOTE: instrument nodes must be at end
 Used by system_mat_instrument
CROSS-REFERENCE INFORMATION
This function calls:
num_elecs NUM_ELECS: number of electrodes attached to model
This function is called by:
show_fem SHOW_FEM: show the EIDORS3D finite element model
system_mat_instrument SYSTEM_MAT_INSTRUMENT:
SOURCE CODE
function fmdl = remove_instrument_electrodes(fmdl)
% pre-delete all 'instrument' nodes
% system matrix can't handle them
% NOTE: instrument nodes must be at end
%
% Used by system_mat_instrument
% (C) 2023 Andy Adler. Licence GPL v2 or v3
   if ~isfield(fmdl,'electrode')
      return % nothing to do
   end
   rmelec = [];
   for i=num_elecs(fmdl):-1:1
      try
         enodes = fmdl.electrode(i).nodes;
         if ischar(enodes) && strcmp(enodes,'instrument');
            rmelec(end+1) = i;
         end
      end
   end
   fmdl.electrode(rmelec)= [];
   if ~isfield(fmdl,'stimulation')
      return % nothing to do
   end
   for i=1:length(fmdl.stimulation)
      fmdl.stimulation(i).stim_pattern(rmelec) = [];
      fmdl.stimulation(i).meas_pattern(:,rmelec) = [];
      try % if it exists
      fmdl.stimulation(i).volt_pattern(rmelec) = [];
      end
   end